### ISSUE TITLE
Create endpoint compatibility checking Coupon validity on ProgrammeStart

### ISSUE THREAD

**Issue by phmasek** [MultinetInteractive/eduadmin-api-phpclient#1]
The EduAdmin API supports checking Coupon validity on ProgrammeStartId. I suggest to add support for this endpoint in the phpclient.

https://api.eduadmin.se/?page=write#operation/V1CouponProgrammeStartIsValidGet

**Comment by itssimple** [comment]
Resolved with PR #2
